In [11]:
import pandas as pd

df = pd.read_csv('Hobt_web.csv')
df

,answer,similar_answer,question,test_year,sub_category,main_category,etc
0,반정규화,NaN,"정규화된 엔티티, 속성, 관계에 대해 시스템의 성능향상과 개발(Development...",2020년 1회 실기,데이터베이스,데이터 입출력 구현,"둘 이상의 릴레이션들에 대하여 조인한 결과를 빈번하게 이용하는 경우, 반정규화 함으..."
1,XML,NaN,"HTML의 단점을 보완한 언어로, SGML의 복잡한 단점을 개선한 다목적 마크업 언...",2020년 1회 실기,프로그래밍언어,통합 구현,NaN
2,살충제 패러독스,NaN,동일한 테스트 게이스로 동일한 절차를 반복 수행하면 새로운 결함을 찾을 수 없다는 ...,2020년 1회 실기,패러다임,서버 프로그램 구현,같은 테스트케이스를 가지고 테스트를 계속해서 반복하면 내성으로 인해 결국은 버그가 ...
3,"결합도, 응집도",NaN,모듈화를 중심으로 하는 소프트웨어 설계 방법에서는 모듈의 독립성을 높게 해주는 것이...,2020년 1회 실기,모듈,서버 프로그램 구현,NaN
4,JSON,NaN,( )은 데이터를 저장하거나 전송할 때 많이 사용되는 경량의 DATA 교환 방식이다...,2020년 1회 실기,프로그래밍언어,인터페이스 구현,NaN
...,...,...,...,...,...,...,...
1229,버블정렬,NaN,인접한 두 원소를 비교하여 큰 값을 오른쪽으로 교환하며 정렬하는 방법,기출 예상 문제,정렬,응용 SW 기초 기술 활용,NaN
1230,선택정렬,NaN,"주어진 배열에서 가장 작은 값을 선택해 맨 앞의 값과 교환하고, 다음으로 작은 값을...",기출 예상 문제,정렬,응용 SW 기초 기술 활용,NaN
1231,전위(Pre-order) 탐색,NaN,루트 노드를 먼저 방문하고 왼쪽 서브트리를 탐색한 후 오른쪽 서브트리를 탐색합니다....,기출 예상 문제,트리 탐색,응용 SW 기초 기술 활용,NaN
1232,후위(Post-order) 탐색,NaN,왼쪽 서브트리를 탐색한 후 오른쪽 서브트리를 탐색하고 마지막으로 루트 노드를 방문합...,기출 예상 문제,트리 탐색,응용 SW 기초 기술 활용,NaN
1233,중위(In-order) 탐색,NaN,왼쪽 서브트리를 탐색한 후 루트 노드를 방문하고 오른쪽 서브트리를 탐색합니다.\n방...,기출 예상 문제,트리 탐색,응용 SW 기초 기술 활용,NaN

In [12]:
# 1. 라이브러리 가져오기
import pymysql

# 2. 접속하기
db = pymysql.connect(
    host='hobtdb.cgvif8lsqknk.us-east-2.rds.amazonaws.com',
    port=3306,
    user='admin',
    passwd='1234qwer',
    db='hobt',
    charset='utf8'
)

In [17]:
# MySQL에 데이터 삽입
cursor = db.cursor()
for _, row in df.iterrows():
  sql = "INSERT INTO test_questions (answer, similar_answer, question, test_year, sub_category, main_category, etc) VALUES (%s, %s, %s, %s, %s, %s, %s)"
  values = (row['answer'], row['similar_answer'], row['question'], row['test_year'], row['sub_category'], row['main_category'], row['etc'])
  cursor.execute(sql, values)
db.commit()

print(cursor.rowcount, "record inserted.")

ProgrammingError: nan can not be used with MySQL

In [18]:
import pymysql
import csv

# MySQL 서버 접속 정보
db = pymysql.connect(
  host="hobtdb.cgvif8lsqknk.us-east-2.rds.amazonaws.com",
  port=3306,
  user="admin",
  password="1234qwer",
  database="hobt",
  charset='utf8mb4',
  cursorclass=pymysql.cursors.DictCursor
)

# CSV 파일 읽기
with open('HoBT_web.csv', newline='', encoding='utf-8') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        # MySQL에 데이터 삽입
        cursor = db.cursor()
        sql = "INSERT INTO test_questions (answer, similar_answer, question, test_year, sub_category, main_category, etc) VALUES (%s, %s, %s, %s, %s, %s, %s)"
        values = (row['answer'], row['similar_answer'], row['question'], row['test_year'], row['sub_category'], row['main_category'], row['etc'])
        cursor.execute(sql, values)
        db.commit()
        print(cursor.rowcount, "record inserted.")

KeyError: 'answer'